; Traits
	const_def
	const TRAIT_CONTACT_BRN
	const TRAIT_CONTACT_PSN
	const TRAIT_CONTACT_PRZ
	const TRAIT_CONTACT_FLINCH
	const TRAIT_CONTACT_CONFUSED
	const TRAIT_CONTACT_IN_LOVE
	const TRAIT_CONTACT_SPORE
	const TRAIT_CONTACT_DAMAGE_ROCK
	const TRAIT_CONTACT_DAMAGE_GROUND
	const TRAIT_CONTACT_DAMAGE_FIRE
	const TRAIT_HOT_COALS
	const TRAIT_BARBS
	const TRAIT_EVASION_ON_SPEED_DIFF
	const TRAIT_ATK_ON_ATK_DIFF
	const TRAIT_COPY_SPD_BUFFS
	const TRAIT_MOVE_DISABLE
	const TRAIT_STEAL_BUFF
	const TRAIT_REVERSE_DEBUFF
	const TRAIT_SPEED_TRANSFORM
	const TRAIT_HEAL_HP_FAINT
	const TRAIT_HEAL_PP_FAINT
	const TRAIT_DAMAGE_FAINT
	const TRAIT_BURN_FAINT
	const TRAIT_POISON_FAINT
	const TRAIT_FREEZE_FAINT
	const TRAIT_CURSE_FAINT
	const TRAIT_ATTACK_OPP_FAINT
	const TRAIT_SP_ATTACK_OPP_FAINT
	const TRAIT_RANDOM_STAT_OPP_FAINT
	const TRAIT_STURDY
	const TRAIT_PERFECT_ACCURACY
	const TRAIT_MOVE_ACC_NON_STAB_MORE
	const TRAIT_SWAP_DEFENSE_BUFFS
	const TRAIT_BOOST_POWER_RAISED_DEF
	const TRAIT_BOOST_PUNCHING
	const TRAIT_BOOST_BITING
	const TRAIT_BOOST_CUTTING
	const TRAIT_BOOST_BEAM
	const TRAIT_BOOST_PERFURATE
	const TRAIT_REDUCE_SELF_RECOIL
	const TRAIT_BOOST_CRIT_DAMAGE
	const TRAIT_REDUCE_CRIT_DAMAGE
	const TRAIT_PSN_DRAIN
	const TRAIT_BRN_DRAIN
	const TRAIT_BOOST_DRAIN
	const TRAIT_BOOST_MULTI_HIT_COUNT
	const TRAIT_BOOST_MULTI_HIT_DAMAGE
	const TRAIT_BOOST_DAMAGE_PER_TURN
	const TRAIT_REDUCE_DAMAGE_PER_TURN
	const TRAIT_BOOST_DAMAGE_PER_TURN_SLOW
	const TRAIT_ATTACK_SPECIAL_ODD_EVEN
	const TRAIT_BOOST_BRN_OPP_ITEM
	const TRAIT_RANDOM_STAT_BRN
	const TRAIT_FIND_BERRY
	const TRAIT_UPGRADE_BERRY
	const TRAIT_BOOST_BERRY
	const TRAIT_CLONE_BERRY
	const TRAIT_RESIST_RANDOM_TYPE
	const TRAIT_ALL_STATS_BOTH_SIDES
	const TRAIT_PARTY_NORMAL_BOOST_DEFENSE
	const TRAIT_PARTY_FIGHTING_BOOST_DEFENSE
	const TRAIT_PARTY_FLYING_BOOST_DEFENSE
	const TRAIT_PARTY_POISON_BOOST_DEFENSE
	const TRAIT_PARTY_GROUND_BOOST_DEFENSE
	const TRAIT_PARTY_ROCK_BOOST_DEFENSE
	const TRAIT_PARTY_STEEL_BOOST_DEFENSE
	const TRAIT_PARTY_BUG_BOOST_DEFENSE
	const TRAIT_PARTY_FIRE_BOOST_DEFENSE
	const TRAIT_PARTY_WATER_BOOST_DEFENSE
	const TRAIT_PARTY_GRASS_BOOST_DEFENSE
	const TRAIT_PARTY_ELECTRIC_BOOST_DEFENSE
	const TRAIT_PARTY_PSYCHIC_BOOST_DEFENSE
	const TRAIT_PARTY_ICE_BOOST_DEFENSE
	const TRAIT_PARTY_DARK_BOOST_DEFENSE
	const TRAIT_REGEN_ON_RAIN
	const TRAIT_RAIN_DURATION
	const TRAIT_RAIN_ON_ENTER
	const TRAIT_REGEN_ON_SUNSHINE
	const TRAIT_SUNSHINE_DURATION
	const TRAIT_SUNSHINE_ON_ENTER
	const TRAIT_REGEN_ON_SANDSTORM
	const TRAIT_SANDSTORM_DURATION
	const TRAIT_SANDSTORM_ON_ENTER ; 
	const TRAIT_HEAL_HP_AND_STATUS
	const TRAIT_RAISE_ATTACK_STAT_LOWERED
	const TRAIT_RAISE_DEFENSE_STAT_LOWERED
	const TRAIT_RAISE_SPEED_STAT_LOWERED
	const TRAIT_RAISE_SP_ATTACK_STAT_LOWERED
	const TRAIT_RAISE_SP_DEFENSE_STAT_LOWERED
	const TRAIT_HEAL_STATUS
	const TRAIT_BOOST_RECOIL
	const TRAIT_RAIN_SPEED
	const TRAIT_RAIN_ACCURACY
	const TRAIT_RAIN_EVASION
	const TRAIT_RAIN_NO_STATUS
	const TRAIT_SUNSHINE_SPEED
	const TRAIT_SUNSHINE_EVASION
	const TRAIT_SUNSHINE_NO_STATUS
	const TRAIT_SANDSTORM_SPEED
	const TRAIT_SANDSTORM_EVASION
	const TRAIT_SANDSTORM_NO_STATUS
	const TRAIT_BRN_IMMUNE
	const TRAIT_BOOST_EFFECT_BRN
	const TRAIT_PSN_IMMUNE
	const TRAIT_BOOST_EFFECT_PSN
	const TRAIT_PRZ_IMMUNE
	const TRAIT_BOOST_EFFECT_PRZ
	const TRAIT_FLINCH_IMMUNE
	const TRAIT_BOOST_EFFECT_FLINCH
	const TRAIT_CONFUSED_IMMUNE
	const TRAIT_BOOST_EFFECT_CONFUSED
	const TRAIT_IN_LOVE_IMMUNE
	const TRAIT_SLEEP_IMMUNE
	const TRAIT_FRZ_IMMUNE
	const TRAIT_BOOST_FREEZE_STATUS
	const TRAIT_PREVENT_ATTACK_DOWN
	const TRAIT_PREVENT_DEFENSE_DOWN
	const TRAIT_PREVENT_SPEED_DOWN
	const TRAIT_PREVENT_SP_ATTACK_DOWN
	const TRAIT_PREVENT_SP_DEFENSE_DOWN
	const TRAIT_PREVENT_ACCURACY_DOWN
	const TRAIT_PREVENT_ALL_DOWN
	const TRAIT_REDUCE_EFFECT_NO_DAMAGE	
	const TRAIT_BOOST_EFFECT_NO_DAMAGE
	const TRAIT_REDUCE_PHYSICAL_TAKEN_TURNS
	const TRAIT_REDUCE_SPECIAL_TAKEN_TURNS
	const TRAIT_BOOST_DAMAGE_WITH_EFFECT
	const TRAIT_REDUCE_EFFECT_WITH_DAMAGE
	const TRAIT_BOOST_EFFECT_WITH_DAMAGE ;
	const TRAIT_CRITICAL_NOT_STAB
	const TRAIT_BOOST_NOT_STAB_WATER_ICE
	const TRAIT_BOOST_NOT_STAB_FIRE_PSYCHIC
	const TRAIT_BOOST_NOT_STAB
	const TRAIT_REDUCE_NOT_STAB ; not stab comes before this
	const TRAIT_BOOST_POWER_BRN_SELF
	const TRAIT_BOOST_ACCURACY_TURN_ZERO
	const TRAIT_REDUCE_DAMAGE_TURN_ZERO
	const TRAIT_GAIN_PP_TURN_ZERO
	const TRAIT_LOWER_ATTACK_TURN_ZERO
	const TRAIT_LOWER_RANDOM_TURN_ZERO; turn 0 comes before this
	const TRAIT_HEAL_AFTER_BERRY
	const TRAIT_HEAL_HP_AFTER_WATER_MOVE
	const TRAIT_BOOST_ATK_ACC_NOT_ATTACKING
	const TRAIT_BOOST_DEF_ACC_NOT_ATTACKING
	const TRAIT_BOOST_SPD_ACC_NOT_ATTACKING
	const TRAIT_BOOST_SPATK_ACC_NOT_ATTACKING
	const TRAIT_ALL_STATS_AFTER_7_TURNS
	const TRAIT_RANDOM_STAT_AFTER_5_TURNS
	const TRAIT_REGEN_FIRST_TURNS ; checks first 3 turns
	const TRAIT_CULL_OPP_LOW_HP ; opp at low hp comes before this
	const TRAIT_REGEN_LOW_HP ; low hp (50%) comes before this
	const TRAIT_ATTACK_BELOW_THIRD
	const TRAIT_DEFENSE_BELOW_THIRD
	const TRAIT_SPEED_BELOW_THIRD
	const TRAIT_SP_ATTACK_BELOW_THIRD
	const TRAIT_SP_DEFENSE_BELOW_THIRD
	const TRAIT_ACCURACY_BELOW_THIRD
	const TRAIT_EVASION_BELOW_THIRD 
	const TRAIT_CRIT_BELOW_THIRD ; low hp (33%) comes before this
	const TRAIT_ATTACK_AFTER_CRIT
	const TRAIT_DEFENSE_AFTER_CRIT
	const TRAIT_SPEED_AFTER_CRIT
	const TRAIT_SP_ATTACK_AFTER_CRIT
	const TRAIT_SP_DEFENSE_AFTER_CRIT
	const TRAIT_REDUCE_CRIT_MORE ; 
	const TRAIT_BOOST_MOVE_SECOND
	const TRAIT_CRITICAL_AFTER_CRIT
	const TRAIT_PASS_STATUS
	const TRAIT_PASS_STATUS_WITH_PHYSICAL
	const TRAIT_STATUS_TO_SLP
	const TRAIT_ATTACK_STATUSED
	const TRAIT_DEFENSE_STATUSED
	const TRAIT_SPEED_STATUSED
	const TRAIT_SP_ATTACK_STATUSED
	const TRAIT_SP_DEFENSE_STATUSED
	const TRAIT_ACCURACY_STATUSED
	const TRAIT_EVASION_STATUSED
	const TRAIT_HEAL_PP_STATUSED
	const TRAIT_REGEN_STATUSED
	const TRAIT_EVASION_WHEN_CONFUSED
	const TRAIT_RANDOM_STAT_WHEN_FLINCHED
	const TRAIT_OPP_SAME_TYPE_DMG_BOOST
	const TRAIT_OPP_SAME_TYPE_CRIT_BOOST
	const TRAIT_BOOST_WEAK_MOVES
	const TRAIT_REDUCE_PSN_AND_POISON
	const TRAIT_REDUCE_BRN_AND_FIRE
	const TRAIT_REDUCE_PRZ_AND_ELECTRIC
	const TRAIT_REDUCE_FLINCH_AND_ROCK
	const TRAIT_REDUCE_SLP_AND_DARK
	const TRAIT_REDUCE_PSN_AND_BUG
	const TRAIT_REDUCE_FRZ_AND_ICE
	const TRAIT_REDUCE_CONFUSE_AND_PSYCHIC
	;
	const TRAIT_REDUCE_WATER_FIRE_HIT
	const TRAIT_REDUCE_ROCK_GROUND_HIT
	const TRAIT_REDUCE_FIGHTING_ICE_HIT
	const TRAIT_REDUCE_POISON_PSYCHIC_HIT
	const TRAIT_REDUCE_FLYING_STEEL_HIT
	const TRAIT_REDUCE_ELECTRIC_DARK_HIT
	const TRAIT_REDUCE_WATER_GRASS_HIT
	;
	const TRAIT_DEFENSE_ICE_FIRE_HIT
	const TRAIT_SPEED_BUG_DARK_HIT
	; 
	const TRAIT_REDUCE_NORMAL
	const TRAIT_REDUCE_NORMAL_MORE
	const TRAIT_REDUCE_NORMAL_ACC
	const TRAIT_BOOST_NORMAL_STATUSED
	; 
	const TRAIT_BOOST_FIGHTING_STATUSED
	; 
	const TRAIT_BOOST_FLYING_SPEED	
	const TRAIT_BOOST_FLYING_STATUSED
	const TRAIT_FLYING_FRZ
	const TRAIT_FLYING_PRZ
	const TRAIT_FLYING_BRN
	const TRAIT_BOOST_FLYING_DURING_WEATHER
	; 
	const TRAIT_REDUCE_POISON_UP_MAIN_STAT
	const TRAIT_BOOST_POISON_STATUSED
	; 
	const TRAIT_BOOST_GROUND_STATUSED
	const TRAIT_RESIST_GROUND_LATER
	; 
	const TRAIT_BOOST_ROCK_DEFENSE
	const TRAIT_BOOST_ROCK_SP_DEFENSE
	const TRAIT_BOOST_ROCK_STATUSED

	const TRAIT_REDUCE_STEEL_MORE
	const TRAIT_BOOST_STEEL_SPEED
	; 
	const TRAIT_BOOST_BUG_HP
	const TRAIT_BOOST_BUG_STATUSED
	;
	const TRAIT_BOOST_FIRE_HP
	const TRAIT_BOOST_FIRE_STATUSED
	const TRAIT_LOWER_SP_ATTACK_FIRE
	;
	const TRAIT_BOOST_WATER_DEFENSE
	const TRAIT_BOOST_WATER_HP
	const TRAIT_BOOST_WATER_STATUSED
	const TRAIT_REDUCE_WATER_UP_MAIN_STAT
	const TRAIT_FRZ_SPD_WITH_WATER
	const TRAIT_LOWER_SP_ATTACK_WATER
	;
	const TRAIT_BOOST_GRASS_HP
	const TRAIT_BOOST_GRASS_STATUSED
	const TRAIT_REDUCE_GRASS_UP_MAIN_STAT
	const TRAIT_PRZ_PSN_WITH_GRASS
	;
	const TRAIT_BOOST_ELECTRIC_SPEED
	const TRAIT_BOOST_ELECTRIC_STATUSED
	const TRAIT_LOWER_SP_ATTACK_ELECTRIC
	;
	const TRAIT_BOOST_PSYCHIC_STATUSED
	const TRAIT_LOWER_SP_ATTACK_PSYCHIC
	;
	const TRAIT_BOOST_ICE_HP
	const TRAIT_BOOST_ICE_STATUSED
	;
	const TRAIT_REDUCE_DARK_UP_MAIN_STAT
	const TRAIT_BOOST_DARK_STATUSED
	;
	const TRAIT_BOOST_NOT_EFFECTIVE
	const TRAIT_SUPER_EFFECTIVE_LOWER_ACC
	const TRAIT_REDUCE_SUPER_EFFECTIVE
	const TRAIT_REDUCE_SUPER_EFFECTIVE_MORE
TRAIT_COUNT EQU const_value

; For support traits, these constants define how they change
SUP_CHANCE_DOWN  EQU 1 << 4 ; %00010000
SUP_EFFECT_DOWN  EQU 2 << 4 ; %00100000
SUP_TRIGGER_ONCE EQU 3 << 4 ; %00110000
SUP_SET_FLAT     EQU 4 << 4 ; %01000000
SUP_UNUSABLE     EQU 5 << 4 ; %01010000
; Support traits that have a reduced chance
SUP_12_PERCENT   EQU 0 ; 1 in 8
SUP_25_PERCENT   EQU 1 ; 2 in 8
SUP_50_PERCENT   EQU 3 ; 4 in 8
SUP_75_PERCENT   EQU 5 ; 6 in 8
SUP_100_PERCENT  EQU 7 ; 8 in 8
; Support traits that use SupportDamageMod
SUP_EFFECT_75    EQU 0
SUP_EFFECT_50    EQU 1
SUP_EFFECT_25    EQU 2
