command: MACRO
	enum \1_command
\1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	enum_start 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command posthiteffects			; 11
	command checkfaint              ; 12
	command buildopponentrage       ; 13
	command poisontarget            ; 14
	command sleeptarget             ; 15
	command draintarget             ; 16
	command eatdream                ; 17
	command burntarget              ; 18
	command freezetarget            ; 19
	command paralyzetarget          ; 1a
	command selfdestruct            ; 1b
	command mirrormove              ; 1c
	command statup                  ; 1d
	command statdown                ; 1f
	command conversion              ; 20
	command resetstats              ; 23
	command forceswitch             ; 24
	command endloop                 ; 25
	command flinchtarget            ; 26
	command ohko                    ; 27
	command recoil                  ; 28
	command mist                    ; 29
	command focusenergy             ; 2a
	command confuse                 ; 2b
	command confusetarget           ; 2c
	command heal                    ; 2d
	command transform               ; 2e
	command screen                  ; 2f
	command poison                  ; 30
	command paralyze                ; 31
	command substitute              ; 32
	command rechargenextturn        ; 33
	command mimic                   ; 34
	command metronome               ; 35
	command leechseed               ; 37
	command disable                 ; 38
	command cleartext               ; 39
	command charge                  ; 3a
	command checkcharge             ; 3b
	command traptarget              ; 3d
	command rampage                 ; 3e
	command checkrampage            ; 3f
	command constantdamage          ; 40
	command counter                 ; 41
	command encore                  ; 42
	command painsplit               ; 43
	command snore                   ; 44
	command conversion2             ; 45
	command lockon                  ; 46
	command sketch                  ; 47
	command defrostopponent         ; 48
	command sleeptalk               ; 49
	command wakeupslap              ; 4a
	command spite                   ; 4b
	command falseswipe              ; 4c
	command healbell                ; 4d
	command kingsrock               ; 4e
	command triplekick              ; 4f
	command kickcounter             ; 50
	command atkdefup                ; 50
	command spatkspdefup            ; 50
	command defspdefup              ; 51
	command arenatrap               ; 52
	command nightmare               ; 53
	command defrost                 ; 54
	command curse                   ; 55
	command protect                 ; 56
	command spikes                  ; 57
	command prismlight              ; 58
	command perishsong              ; 59
	command startsandstorm          ; 5a
	command endure                  ; 5b
	command checkcurl               ; 5c
	command rolloutpower            ; 5e
	command furycutter              ; 5f
	command attract                 ; 60
	command modtype			        ; 62
	command damagecalc              ; 64
	command safeguard               ; 65
	command checksafeguard          ; 66
	command getmagnitude            ; 67
	command batonpass               ; 68
	command pursuit                 ; 69
	command clearhazards            ; 6a
	command healmorn                ; 6b
	command healday                 ; 6c
	command healnite                ; 6d
	command hiddenpower             ; 6e
	command startrain               ; 6f
	command startsun                ; 70
	command attackup                ; 71
	command defenseup               ; 72
	command speedup                 ; 73
	command specialattackup         ; 74
	command specialdefenseup        ; 75
	command accuracyup              ; 76
	command evasionup               ; 77
	command attackup2               ; 78
	command defenseup2              ; 79
	command speedup2                ; 7a
	command specialattackup2        ; 7b
	command specialdefenseup2       ; 7c
	command accuracyup2             ; 7d
	command evasionup2              ; 7e
	command attackdown              ; 7f
	command defensedown             ; 80
	command speeddown               ; 81
	command specialattackdown       ; 82
	command specialdefensedown      ; 83
	command accuracydown            ; 84
	command evasiondown             ; 85
	command attackdown2             ; 86
	command defensedown2            ; 87
	command speeddown2              ; 88
	command specialattackdown2      ; 89
	command specialdefensedown2     ; 8a
	command accuracydown2           ; 8b
	command evasiondown2            ; 8c
	command statupmessage           ; 8d
	command statdownmessage         ; 8e
	command statupfailtext          ; 8f
	command statdownfailtext        ; 90
	command effectchance            ; 91
	command statdownanim            ; 92
	command statupanim              ; 93
	command switchturn              ; 94
	command fakeout                 ; 95
	command bellydrum               ; 96
	command psychup                 ; 97
	command rage                    ; 98
	command doubleflyingdamage      ; 99
	command doubleundergrounddamage ; 9a
	command mirrorcoat              ; 9b
	command checkfuturesight        ; 9c
	command futuresight             ; 9d
	command doubleminimizedamage    ; 9e
	command skipsuncharge           ; 9f
	command thunderaccuracy         ; a0
	command teleport                ; a2
	command ragedamage              ; a3
	command resettypematchup        ; a4
	command allstatsup              ; a6
	command raisesubnoanim          ; a7
	command lowersubnoanim          ; a9
	command clearmissdamage         ; aa
	command movedelay               ; ab
	command moveanim                ; ac
	command tristatuschance         ; ad
	command supereffectivelooptext  ; ae
	command startloop               ; af
	command curl                    ; b0
	command burn					; b1
	command weightdamage			; b2
	command venoshock				; b3
	command brickbreak				; b4
	command defspdefdown			; b5
	command fireflick				; b6
	command stampede				; b7
	command jetstream				; b8
	command wakeupfoe				; b9
	command getwildstorm			; ba
	command fireplay				; bc
	command recalcstats				; bd
	command acupressure				; be
	command slowhit  				; 
	command postbuffeffects         ;
	command postdebuffeffects       ;
	command switchout               ;
	command setfiveturns            ;

	enum_start $fe
	command endturn                 ; fe
	command endmove                 ; ff
